export interface ProductItem {
  id: string;
  name: string;
  category: string;
  categoryId: string;
  desc: string;
  image: string;
  badge: string;
  features: string[];
  specs: { label: string; value: string }[];
}

export interface CategoryItem {
  id: string;
  label: string;
  desc?: string;
  icon?: string;
  count?: number;
}

export const CATEGORIES: CategoryItem[] = [
  { id: "all", label: "All Products", count: 54 },
  { id: "infusion", label: "Infusion / Perfusion Range", count: 12 },
  { id: "anesthesia", label: "Anesthesia", count: 10 },
  { id: "urology", label: "Urology", count: 13 },
  { id: "gynecology", label: "Gynecology", count: 3 },
  { id: "gastroenterology", label: "Gastroenterology", count: 3 },
  { id: "cardiology", label: "Cardiology", count: 2 },
  { id: "surgical", label: "General Surgical Disposables", count: 6 },
  { id: "mecca-labs", label: "Mecca Labs", count: 5 },
];

export const PRODUCTS: ProductItem[] = [
  /* ═══════════════════════════════════════════════════════════════════
     1. INFUSION / PERFUSION RANGE (12 Products)
     ═══════════════════════════════════════════════════════════════════ */
  {
    id: "meca-care-non-vented-iv-set",
    name: "MECA CARE NON VENTED I.V. SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Sterile non-vented intravenous infusion set designed for gravity feed infusion from collapsible fluid bags and non-rigid IV containers.",
    image: "/Infusion&Perfusion/image14.jpg",
    badge: "ISO 13485 Certified",
    features: [
      "Sharp non-vented piercing spike for collapsible IV containers",
      "Clear cylindrical drip chamber with integrated 15 micron fluid filter",
      "Kink-resistant medical grade PVC tubing (150cm / 180cm)",
      "Precision roller clamp for accurate flow rate regulation",
      "Self-sealing latex / latex-free injection site & luer lock connector",
    ],
    specs: [
      { label: "Spike Type", value: "Non-Vented Piercing Spike" },
      { label: "Drip Rate", value: "20 drops/ml (Macro)" },
      { label: "Tubing Length", value: "150 cm / 180 cm" },
      { label: "Fluid Filter", value: "15 micron fluid mesh" },
      { label: "Sterilization", value: "EO Gas (ISO 11135)" },
      { label: "Packaging", value: "Individual Sterile Blister, Box of 25" },
    ],
  },
  {
    id: "meca-care-vented-iv-set",
    name: "MECA CARE VENTED I.V. SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Premium vented IV administration set with built-in air vent and hydrophobic antibacterial filter, engineered for glass bottles and rigid containers.",
    image: "/Infusion&Perfusion/image13.jpg",
    badge: "Medical Grade PVC",
    features: [
      "Vented spike with 1.2 micron hydrophobic bacterial air filter and snap cap",
      "Soft, clear flexible drip chamber for rapid fluid level viewing",
      "Smooth roller clamp provides micro-fine fluid control",
      "Latex-free Y-injection port for supplementary medication delivery",
      "Universal luer lock adapter ensures leak-proof vascular connection",
    ],
    specs: [
      { label: "Spike Type", value: "Vented Spike with Air Inlet" },
      { label: "Drip Rate", value: "20 drops/ml" },
      { label: "Air Filter", value: "1.2 micron Hydrophobic" },
      { label: "Tubing Length", value: "150 cm / 180 cm DEHP-Free" },
      { label: "Sterilization", value: "EO Sterile, Non-Pyrogenic" },
      { label: "Packaging", value: "Rigid Blister Pack, Box of 25" },
    ],
  },
  {
    id: "meca-care-blood-administration-set",
    name: "MECA CARE BLOOD ADMINISTRATION SET / B.T. SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Heavy-duty sterile blood administration set equipped with a 200 micron blood filter mesh to trap clots and cellular aggregates during transfusion.",
    image: "/Infusion&Perfusion/image3.jpg",
    badge: "200 Micron Mesh",
    features: [
      "Extra-large cylindrical drip chamber with integrated 200µm filter",
      "Heavy-duty spike penetrates blood bags cleanly without coring",
      "Smooth roller clamp for precise transfusion velocity adjustment",
      "Kink-resistant high-flow medical PVC tubing with flashbulb injection site",
      "Fitted with 18G / 19G needle for immediate clinical readiness",
    ],
    specs: [
      { label: "Filter Size", value: "200 micron nylon filter mesh" },
      { label: "Drip Factor", value: "20 drops/ml" },
      { label: "Needle Gauge", value: "18G / 19G mounted needle" },
      { label: "Tubing Length", value: "150 cm" },
      { label: "Compatibility", value: "Whole blood & packed red blood cells" },
      { label: "Sterilization", value: "ETO Gas (ISO 11135)" },
    ],
  },
  {
    id: "meca-care-micro-drip-set",
    name: "MECA CARE MICRO DRIP SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Precision pediatric micro infusion set with 60 drops/ml calibrated metal cannula dropper for delicate fluid management and critical medication dosing.",
    image: "/Infusion&Perfusion/image4.jpg",
    badge: "Micro Drip 60 Drops/ml",
    features: [
      "Calibrated stainless steel micro-dropper (60 drops = 1 ml ± 0.1ml)",
      "High accuracy fluid dosing for neonatal, pediatric, and ICU therapy",
      "Transparent flexible drip chamber with 15 micron fluid filter",
      "Micro-fine roller clamp allows ultra-precise drops adjustment",
      "DEHP-Free medical grade tubing with latex-free injection site",
    ],
    specs: [
      { label: "Drip Rate", value: "60 drops/ml (Micro Drip)" },
      { label: "Dropper Cannula", value: "Surgical Stainless Steel" },
      { label: "Tubing Length", value: "150 cm DEHP-Free" },
      { label: "Filter Size", value: "15 micron fluid filter" },
      { label: "Sterilization", value: "EO Sterile" },
      { label: "Packaging", value: "Medical Blister, Box of 25" },
    ],
  },
  {
    id: "meca-care-measured-volume-burette-set",
    name: "MECA CARE MEASURED VOLUME BURETTE SET / M.V. SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Measured volume burette set featuring a 100ml / 110ml / 150ml graduated cylinder chamber with automatic shut-off floating valve for controlled medication delivery.",
    image: "/Infusion&Perfusion/image5.jpg",
    badge: "Calibrated Burette",
    features: [
      "100ml / 110ml / 150ml clear calibrated chamber with bold graduation markings",
      "Automatic floating disc valve prevents air entry after chamber drains",
      "Built-in injection port on burette cap for aseptic drug additive addition",
      "Micro-dropper calibrated at 60 drops/ml for pediatric precision",
      "Secondary roller clamp and slide clamp for total flow shutoff",
    ],
    specs: [
      { label: "Chamber Capacity", value: "100 ml / 110 ml / 150 ml graduated" },
      { label: "Drip Rate", value: "60 drops/ml" },
      { label: "Shut-Off Valve", value: "Auto floating disc valve" },
      { label: "Compliance", value: "ISO 8536-5 Compliant" },
      { label: "Sterility", value: "Non-Toxic, Non-Pyrogenic, EO Sterile" },
      { label: "Packaging", value: "Individually packed in HM pouch/blister" },
    ],
  },
  {
    id: "scalp-vein-set",
    name: "SCALP VEIN SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Butterfly scalp vein infusion needle with flexible textured wings for short-term venipuncture and peripheral vascular access.",
    image: "/Infusion&Perfusion/image6.jpg",
    badge: "Color Coded Wings",
    features: [
      "Color-coded butterfly wings conform to international gauge standards",
      "Ultra-sharp 3-bevel siliconized stainless steel needle reduces patient pain",
      "Thin-wall cannula design guarantees higher flow rates",
      "Kink-resistant 30cm flexible PVC extension tube",
      "Female luer lock adapter fits all standard infusion apparatus",
    ],
    specs: [
      { label: "Gauges Available", value: "18G, 19G, 20G, 21G, 22G, 23G, 24G, 25G, 27G" },
      { label: "Tube Length", value: "30 cm flexible PVC" },
      { label: "Needle Point", value: "Siliconized 3-facet bevel" },
      { label: "Connector", value: "Female Luer Lock with plug" },
      { label: "Sterilization", value: "EO Gas" },
      { label: "Packaging", value: "Box of 100 sterile units" },
    ],
  },
  {
    id: "meca-care-scalp-vein-set",
    name: "MECA CARE SCALP VEIN SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Clinical grade scalp vein set manufactured with medical-grade AISI 304 stainless steel needle and siliconized coating for painless pediatric and geriatric infusions.",
    image: "/Infusion&Perfusion/image7.jpg",
    badge: "AISI 304 Steel",
    features: [
      "Siliconized needle surface ensures smooth, drag-free vein penetration",
      "Non-slip textured butterfly wings allow firm grip during insertion",
      "Crystal-clear tubing provides instant visual flashback of blood",
      "Non-pyrogenic, non-toxic biocompatible formulation",
      "Individual peel-open blister packaging ensures guaranteed sterility",
    ],
    specs: [
      { label: "Needle Material", value: "AISI 304 Stainless Steel" },
      { label: "Gauges", value: "19G to 27G" },
      { label: "Extension Length", value: "30 cm" },
      { label: "Hub Type", value: "Standard Luer Lock" },
      { label: "Sterilization", value: "EO Gas" },
      { label: "Shelf Life", value: "5 Years" },
    ],
  },
  {
    id: "top-scalp-vein-set",
    name: "TOP SCALP VEIN SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Premium high-flow scalp vein infusion set optimized for stable venous anchoring, blood sampling, and prolonged infusion sessions.",
    image: "/Infusion&Perfusion/image8.jpg",
    badge: "Japanese Bevel",
    features: [
      "Ergonomic wing curvature conforms naturally to patient skin contour",
      "High-grade electro-polished needle minimizes vessel wall trauma",
      "Secure luer lock connector fits all standard infusion and syringe lines",
      "Rigorous 100% inline quality tested for leak-proof security",
      "Ideal for fragile veins in neonatal, pediatric, and oncology care",
    ],
    specs: [
      { label: "Gauges", value: "20G, 21G, 22G, 23G, 24G, 25G" },
      { label: "Wing Material", value: "Medical Grade Soft PVC" },
      { label: "Needle Bevel", value: "Japanese 3-facet back cut" },
      { label: "Sterility", value: "ETO Sterile" },
      { label: "Packaging", value: "Individual Blister, Box of 100" },
    ],
  },
  {
    id: "meca-care-iv-cannula",
    name: "MECA CARE I.V. CANNULA",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "High-precision intravenous cannula with injection port and wings, manufactured with radiopaque FEP/PTFE catheter for atraumatic vein cannulation.",
    image: "/Infusion&Perfusion/image9.jpg",
    badge: "FEP Radiopaque",
    features: [
      "Siliconized stainless steel needle with ultra-sharp 3-facet back cut",
      "Flexible FEP/PTFE radiopaque cannula tubing for X-ray visibility",
      "Color-coded wings for instant international gauge size identification",
      "Self-sealing silicone injection valve with snap-fit cap for port access",
      "Transparent flashback chamber provides immediate confirmation of venipuncture",
    ],
    specs: [
      { label: "Gauges Available", value: "14G, 16G, 18G, 20G, 22G, 24G, 26G" },
      { label: "Flow Rate", value: "13 ml/min (24G) to 270 ml/min (14G)" },
      { label: "Catheter Material", value: "Radiopaque FEP / PTFE" },
      { label: "Needle Point", value: "3-bevel back cut needle" },
      { label: "Packaging", value: "Rigid blister pack, Box of 50" },
      { label: "Certifications", value: "CE 0123 / ISO 13485" },
    ],
  },
  {
    id: "meca-care-syringe-with-needle",
    name: "MECA CARE SYRINGE WITH NEEDLE",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Sterile 3-piece disposable medical syringe with mounted ultra-fine hypodermic needle, high-transparency barrel, and smooth plunger gasket.",
    image: "/Infusion&Perfusion/image12.jpg",
    badge: "3-Piece Precision",
    features: [
      "Crystal-clear medical polypropylene barrel for unobstructed fluid inspection",
      "Bold, permanent graduation markings ensure precise dosage measurement",
      "Smooth double-contact rubber gasket prevents medication back-leakage",
      "Pre-mounted ultra-sharp hypodermic needle for immediate clinical injection",
      "Latex-free and pyrogen-free sterile blister pouch packaging",
    ],
    specs: [
      { label: "Volumes", value: "1 ml, 2 ml, 3 ml, 5 ml, 10 ml, 20 ml, 50 ml" },
      { label: "Needle Size", value: "Mounted 21G - 26G options" },
      { label: "Gasket Material", value: "Latex-free synthetic elastomer" },
      { label: "Barrel Material", value: "High-clarity Polypropylene (PP)" },
      { label: "Sterilization", value: "EO Gas (ISO 11135)" },
      { label: "Standards", value: "ISO 7886-1 Compliant" },
    ],
  },
  {
    id: "pediatric-infusion-set",
    name: "PEDIATRIC INFUSION SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Specialized pediatric intravenous giving set engineered with micro-drip chamber, low prime volume, and integrated safety clamp.",
    image: "/Infusion&Perfusion/image10.jpg",
    badge: "Neonatal Safe",
    features: [
      "Engineered specifically for neonatal and pediatric clinical care",
      "Accurate 60 drops/ml micro-metered fluid delivery",
      "Low priming volume (< 12 ml) minimizes medication waste",
      "Needle-free Y-injection port for safe drug administration",
      "Kink-proof DEHP-free medical grade tubing",
    ],
    specs: [
      { label: "Drip Rate", value: "60 drops/ml (Micro)" },
      { label: "Prime Volume", value: "< 12 ml low volume" },
      { label: "Filter Size", value: "15 micron fluid filter" },
      { label: "Tubing", value: "DEHP-Free Medical PVC" },
      { label: "Connector", value: "Male Luer Lock" },
      { label: "Sterility", value: "EO Sterile" },
    ],
  },
  {
    id: "blood-administration-set-standard",
    name: "BLOOD ADMINISTRATION SET",
    category: "Infusion / Perfusion Range",
    categoryId: "infusion",
    desc: "Clinical standard blood transfusion apparatus for gravity transfusion of whole blood, red cells, and fresh frozen plasma.",
    image: "/Infusion&Perfusion/image11.jpg",
    badge: "Transfusion Grade",
    features: [
      "Cylindrical drip chamber with large surface area 200 micron filter",
      "Prevents clotting while maintaining high transfusion velocity",
      "Ergonomic roller clamp for steady flow regulation",
      "Standard luer slip / luer lock needle fitting",
      "Fully compliant with ISO 1135-4 transfusion standards",
    ],
    specs: [
      { label: "Filter Size", value: "200 micron mesh" },
      { label: "Spike Type", value: "Piercing trocar with cap" },
      { label: "Drip Rate", value: "20 drops/ml" },
      { label: "Tubing Length", value: "150 cm kink-resistant" },
      { label: "Sterilization", value: "ETO Gas" },
      { label: "Packaging", value: "Medical Pouch, Box of 25" },
    ],
  },

  /* ═══════════════════════════════════════════════════════════════════
     2. ANESTHESIA (10 Products)
     ═══════════════════════════════════════════════════════════════════ */
  {
    id: "endotracheal-tube-plain",
    name: "ENDOTRACHEAL TUBE (PLAIN)",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Uncuffed endotracheal tube made of thermosensitive medical-grade PVC, featuring Murphy eye, radiopaque line, and accurate depth markings.",
    image: "/Anesthesia/image1.jpg",
    badge: "Thermosensitive PVC",
    features: [
      "Thermosensitive PVC softens at body temperature for patient comfort",
      "Beveled tip designed for atraumatic vocal cord passage",
      "Murphy eye provides alternative airway path if tip is occluded",
      "Clear centimeter depth markings for accurate positioning",
      "Non-toxic, non-irritant smooth finish compliant with ISO 5356-1",
    ],
    specs: [
      { label: "Sizes (ID)", value: "2.0 mm to 6.5 mm" },
      { label: "Type", value: "Uncuffed / Plain" },
      { label: "Connector", value: "15 mm standard ISO connector" },
      { label: "Line", value: "Full length radiopaque stripe" },
      { label: "Sterilization", value: "EO Gas" },
      { label: "Packaging", value: "Individual Sterile Blister" },
    ],
  },
  {
    id: "endotracheal-tube-cuffed",
    name: "ENDOTRACHEAL TUBE (CUFFED)",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Cuffed endotracheal tube with high-volume low-pressure (HVLP) cuff for secure tracheal sealing during mechanical ventilation and anesthesia.",
    image: "/Anesthesia/image2.jpg",
    badge: "HVLP Soft Cuff",
    features: [
      "Soft thin-walled cuff creates gentle uniform seal with minimal tracheal pressure",
      "Pilot balloon with one-way valve confirms cuff inflation status",
      "Full-length X-ray opaque line for radiographic tube positioning",
      "Kink-resistant clear medical PVC construction",
      "Pre-attached standard 15mm male connector",
    ],
    specs: [
      { label: "Sizes (ID)", value: "3.0 mm to 10.0 mm" },
      { label: "Cuff Type", value: "High Volume Low Pressure (HVLP)" },
      { label: "Pilot Balloon", value: "Self-sealing valve with size imprint" },
      { label: "Connector", value: "Standard 15 mm ISO 5356-1" },
      { label: "Certifications", value: "CE 0123 / ISO 13485" },
      { label: "Sterilization", value: "ETO Sterile" },
    ],
  },
  {
    id: "oxygen-mask",
    name: "OXYGEN MASK",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Ergonomic adult and pediatric oxygen delivery mask with adjustable nose clip, elastic headband, and 2-meter star-lumen crush-resistant tubing.",
    image: "/Anesthesia/image3.jpg",
    badge: "Crush-Resistant",
    features: [
      "Anatomically contoured shape for comfortable, leak-free facial fit",
      "Soft rolled edges prevent pressure sores during extended use",
      "Adjustable aluminum nose clip ensures snug nasal bridge seal",
      "Star-lumen anti-crush tubing maintains oxygen flow even if kinked",
      "Latex-free wide elastic strap for secure patient positioning",
    ],
    specs: [
      { label: "Sizes", value: "Adult (Elongated / Standard), Pediatric" },
      { label: "Tubing Length", value: "200 cm Star Lumen Crush-Resistant" },
      { label: "Material", value: "Clear Non-Toxic Medical Grade PVC" },
      { label: "Connector", value: "Universal funnel connector" },
      { label: "Standard", value: "ISO 13485 / CE Marked" },
      { label: "Packaging", value: "Individually poly-packed" },
    ],
  },
  {
    id: "oxygen-mask-with-nebulizer",
    name: "OXYGEN MASK WITH NEBULIZER",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Complete aerosol therapy kit including high-efficiency 6ml / 8ml nebulizer medication chamber, aerosol mask, and connecting tube.",
    image: "/Anesthesia/image4.jpg",
    badge: "Aerosol Therapy",
    features: [
      "High-output nebulization produces optimal respirable aerosol particles (MMAD < 5µm)",
      "360-degree leak-proof chamber functions even in tilted patient positions",
      "Transparent graduated jar for precise medication dosage measurement",
      "Soft mask with wide elastic strap for prolonged respiratory therapy",
      "Universal oxygen source connector compatible with hospital flowmeters",
    ],
    specs: [
      { label: "Jar Capacity", value: "6 ml / 8 ml graduated" },
      { label: "Particle Size", value: "MMAD < 5 microns" },
      { label: "Output Rate", value: "> 0.2 ml/min" },
      { label: "Mask Type", value: "Adult / Pediatric soft PVC" },
      { label: "Tubing", value: "200 cm oxygen connecting tube" },
      { label: "Sterility", value: "Clean packed / Sterile options" },
    ],
  },
  {
    id: "nasal-cannula-twin-set",
    name: "NASAL CANNULA / TWIN SET OXYGEN TUBE",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Soft curved-prong nasal oxygen cannula designed for gentle low-to-medium flow oxygen delivery with over-the-ear comfort harness.",
    image: "/Anesthesia/image5.jpg",
    badge: "Ultra-Soft Prongs",
    features: [
      "Curved flexible nasal tips deliver smooth airflow directly into nostrils",
      "Over-the-ear harness allows freedom of movement for active patients",
      "Anti-crush star-lumen tube ensures uninterrupted flow",
      "Soft, lightweight biocompatible medical PVC material",
      "Latex-free and DEHP-free options available",
    ],
    specs: [
      { label: "Sizes Available", value: "Neonatal, Infant, Pediatric, Adult" },
      { label: "Prong Type", value: "Curved soft nasal prongs" },
      { label: "Tubing Length", value: "Star-lumen anti-kink 2.1m (7 ft)" },
      { label: "Material", value: "Ultra-soft medical PVC" },
      { label: "Standard", value: "CE / ISO 13485" },
    ],
  },
  {
    id: "nasal-oxygen-catheter",
    name: "NASAL OXYGEN CATHETER",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Single-use nasal catheter with multiple lateral eye perforations for deep pharyngeal and direct nasal oxygen supplementation.",
    image: "/Anesthesia/image6.jpg",
    badge: "Multi-Hole Pharyngeal",
    features: [
      "Multiple micro-drilled lateral eyes distribute oxygen evenly without mucosal irritation",
      "Smooth rounded bullet tip ensures painless insertion",
      "Color-coded funnel connector for instant size identification",
      "Frosted surface finish facilitates effortless tube introduction",
      "DEHP-Free medical grade PVC formulation",
    ],
    specs: [
      { label: "Sizes", value: "Fr 8, 10, 12, 14" },
      { label: "Length", value: "40 cm" },
      { label: "Tip Type", value: "Soft rounded open tip with 8 lateral holes" },
      { label: "Material", value: "Kink-resistant Medical PVC" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "guedel-airways",
    name: "GUEDEL AIRWAYS",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Color-coded Guedel oropharyngeal airway with rigid bite block to prevent airway occlusion and protect against patient bite during recovery.",
    image: "/Anesthesia/image7.jpg",
    badge: "ISO 5364 Standard",
    features: [
      "Color-coded bite blocks conform to international standard sizes",
      "Smooth curved profile follows anatomical contour of the pharynx",
      "Rigid bite-resistant central core prevents tongue collapse and bite injury",
      "Smooth atraumatic finish protects oral tissues from trauma",
      "Flanged end rests securely against lips to prevent deep slippage",
    ],
    specs: [
      { label: "Sizes", value: "000 (40mm), 00 (50mm), 0 (60mm), 1 (70mm), 2 (80mm), 3 (90mm), 4 (100mm), 5 (110mm), 6 (120mm)" },
      { label: "Bite Block", value: "Color-coded reinforced polymer" },
      { label: "Body Material", value: "Semi-rigid Polyethylene" },
      { label: "Standard", value: "ISO 5364" },
      { label: "Packaging", value: "Individual sterile peel pack" },
    ],
  },
  {
    id: "suction-catheter",
    name: "SUCTION CATHETER",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Sterile bronchial and tracheobronchial suction catheter with thumb control valve and lateral eyes for clearing airway secretions.",
    image: "/Anesthesia/image8.jpg",
    badge: "Vacuum Control Vent",
    features: [
      "Soft rounded tip with two offset lateral eyes maximizes suction efficiency",
      "Finger-tip vacuum control valve for instant suction regulation",
      "Frosted kink-resistant tubing glides smoothly inside endotracheal tubes",
      "Color-coded connector for immediate size selection",
      "Graduated depth markings for precise insertion control",
    ],
    specs: [
      { label: "Sizes", value: "Fr 6, 8, 10, 12, 14, 16, 18" },
      { label: "Length", value: "50 cm" },
      { label: "Connector Type", value: "Thumb control vent / Plain funnel" },
      { label: "Tip Design", value: "Atraumatic soft rounded tip" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "three-way-stop-cock",
    name: "THREE WAY STOP COCK",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "High-pressure 3-way stopcock with 360-degree rotating lever, two female luer locks, and one male luer slip/lock for multi-line IV infusion.",
    image: "/Anesthesia/image9.jpg",
    badge: "360° Flow Control",
    features: [
      "360-degree smooth handle rotation indicates active flow channels with clear arrows",
      "Transparent polycarbonate body allows immediate bubble inspection",
      "Fully lipid-resistant and compatible with all IV medications",
      "Universal 6% luer taper ensures leak-free fit with all standard infusion lines",
      "Minimal residual dead space volume",
    ],
    specs: [
      { label: "Pressure Rating", value: "Up to 4.5 bar (65 psi) / 500 psi lipid resistant" },
      { label: "Ports", value: "2 Female Luer + 1 Male Luer Lock" },
      { label: "Handle Rotation", value: "360° rotation with arrow indicators" },
      { label: "Material", value: "Polycarbonate (Lipid Resistant)" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "pressure-monitoring-line-anesthesia",
    name: "PRESSURE MONITORING LINE",
    category: "Anesthesia",
    categoryId: "anesthesia",
    desc: "Non-compliant rigid extension line designed for invasive arterial and central venous pressure monitoring without waveform distortion.",
    image: "/Anesthesia/image10.jpg",
    badge: "500 PSI Rated",
    features: [
      "Thick-walled rigid tubing transmits hydraulic pulse pressure waves accurately without damping",
      "Dual luer locks guarantee secure high-pressure sealing",
      "Crystal-clear tubing for air bubble detection",
      "DEHP-free formulation ensures biocompatibility",
      "Available in various custom clinical lengths",
    ],
    specs: [
      { label: "Lengths Available", value: "10 cm, 25 cm, 50 cm, 100 cm, 150 cm, 200 cm" },
      { label: "Pressure Rating", value: "Up to 500 psi (35 bar)" },
      { label: "Internal Diameter", value: "1.0 mm - 1.5 mm" },
      { label: "Fittings", value: "Male-to-Female / Male-to-Male Luer Lock" },
      { label: "Material", value: "High-density Polyurethane / PVC" },
      { label: "Sterilization", value: "EO Sterile" },
    ],
  },

  /* ═══════════════════════════════════════════════════════════════════
     3. UROLOGY (13 Products)
     ═══════════════════════════════════════════════════════════════════ */
  {
    id: "urine-bag-hanging-reverse",
    name: "URINE BAG WITH HANGING & REVERSE ARRANGEMENT",
    category: "Urology",
    categoryId: "urology",
    desc: "Closed urinary drainage system with universal hanger, reinforced eyelets, non-return flutter valve, and bottom push-pull outlet.",
    image: "/Urology/image1.jpg",
    badge: "Anti-Reflux Valve",
    features: [
      "Sturdy double hanger and strap for secure bed rail mounting",
      "Anti-reflux flutter valve prevents retrograde infection",
      "Clear 100ml graduation increments up to 2000ml",
      "Kink-resistant wide-bore drainage tube ensures unobstructed flow",
      "Dog-bone sampling port for aseptic needle aspiration",
    ],
    specs: [
      { label: "Capacity", value: "2000 ml" },
      { label: "Tube Length", value: "90 cm / 100 cm kink-resistant" },
      { label: "Valve Type", value: "Non-Return Flutter Valve (NRV)" },
      { label: "Outlet", value: "Push-Pull T-Tap / Bottom Drain" },
      { label: "Sterilization", value: "EO Sterile" },
      { label: "Packaging", value: "Medical Blister / Pouch" },
    ],
  },
  {
    id: "urine-bag-plain",
    name: "URINE BAG (PLAIN w/out HANGER)",
    category: "Urology",
    categoryId: "urology",
    desc: "Standard 2000ml urine collection bag with universal tapered connector, anti-reflux valve, and top hanging punch holes.",
    image: "/Urology/image2.jpg",
    badge: "2000ml Graduated",
    features: [
      "Economical, reliable urine collection for short-term and post-operative catheterization",
      "Clear semi-transparent front sheet for visual volume assessment",
      "Reinforced top punch holes for versatile hanging hook placement",
      "Molded conical connector fits all standard Foley and Nelaton catheters",
      "Integrated non-return valve prevents backflow of urine",
    ],
    specs: [
      { label: "Volume", value: "2000 ml" },
      { label: "Material", value: "Medical Grade PVC" },
      { label: "Tube Length", value: "90 cm flexible tube" },
      { label: "Valve", value: "Integrated Anti-Reflux Valve" },
      { label: "Sterility", value: "Sterile / Non-Sterile options" },
    ],
  },
  {
    id: "paediatric-urine-collection-bag",
    name: "PAEDIATRIC URINE COLLECTION BAG",
    category: "Urology",
    categoryId: "urology",
    desc: "Sterile pediatric urine specimen bag with hypoallergenic medical adhesive foam for infant and toddler urine collection.",
    image: "/Urology/image3.jpg",
    badge: "Hypoallergenic Foam",
    features: [
      "Skin-friendly adhesive foam pad conforms comfortably to infant perineal anatomy",
      "Leak-proof adhesive seal prevents specimen contamination",
      "Clear graduated markings up to 100ml for precise volume evaluation",
      "Sterile individual packaging ensures contamination-free collection",
      "Easy peel-and-apply application suitable for boys and girls",
    ],
    specs: [
      { label: "Capacity", value: "100 ml graduated" },
      { label: "Adhesive Type", value: "Hypoallergenic medical grade foam adhesive" },
      { label: "Gender", value: "Unisex design for male and female infants" },
      { label: "Material", value: "Soft transparent Polyethylene" },
      { label: "Sterilization", value: "ETO Gas" },
    ],
  },
  {
    id: "uromesare",
    name: "UROMESARE",
    category: "Urology",
    categoryId: "urology",
    desc: "Precision hourly urine volume meter with multi-chamber burette and 2000ml drainage bag for critical care and ICU output monitoring.",
    image: "/Urology/image4.jpg",
    badge: "ICU Hourly Meter",
    features: [
      "Multi-chamber measured volume meter with 1ml increments up to 50ml and 5ml up to 400ml",
      "Integrated hydrophobic air vent prevents airlock and facilitates accurate readings",
      "Bottom bypass lever for rapid dumping into main 2000ml collection bag",
      "Needleless sampling port for contamination-free urine specimen collection",
      "Crucial for ICU kidney perfusion and hemodynamic monitoring",
    ],
    specs: [
      { label: "Meter Chamber", value: "400 ml / 500 ml calibrated (1ml micro markings)" },
      { label: "Bag Capacity", value: "2000 ml drainage bag" },
      { label: "Tube", value: "120 cm kink-resistant silicone-treated tube" },
      { label: "Sampling Port", value: "Needleless needle sampling port" },
      { label: "Hanger", value: "Double universal hanging hook" },
      { label: "Sterilization", value: "EO Sterile" },
    ],
  },
  {
    id: "male-external-catheter",
    name: "MALE EXTERNAL CATHETER",
    category: "Urology",
    categoryId: "urology",
    desc: "100% natural latex penile sheath external catheter with adhesive foam strip for non-invasive male urinary incontinence management.",
    image: "/Urology/image5.jpg",
    badge: "Anti-Twist Funnel",
    features: [
      "Soft, elastic latex sheath rolls on smoothly without skin constriction",
      "Reinforced funnel tip prevents twisting and allows continuous urine outflow",
      "Includes skin-friendly adhesive foam band to ensure secure placement",
      "Compatible with all standard leg and night urine collection bags",
      "Non-invasive alternative to indwelling catheters",
    ],
    specs: [
      { label: "Sizes Available", value: "Small (25mm), Medium (30mm), Large (35mm), X-Large (40mm)" },
      { label: "Material", value: "100% Medical Grade Latex" },
      { label: "Fixation", value: "Double-sided adhesive foam strip" },
      { label: "Tip Design", value: "Reinforced anti-kink funnel tip" },
      { label: "Packaging", value: "Individually packed, Box of 50" },
    ],
  },
  {
    id: "nelaton-urethral-catheter",
    name: "NELATON / URETHRAL CATHETER",
    category: "Urology",
    categoryId: "urology",
    desc: "Single-use intermittent urinary catheter with soft rounded closed tip and two lateral eyelets for rapid bladder drainage.",
    image: "/Urology/image6.jpg",
    badge: "Atraumatic Tip",
    features: [
      "Satin-smooth frosted PVC surface minimizes friction during urethral passage",
      "Distal end features two offset lateral eyes for maximum flow without blockage",
      "Color-coded funnel connector indicates French size for instant identification",
      "Suitable for diagnostic catheterization, post-op drainage, and bladder instillation",
      "DEHP-Free medical grade PVC formulation",
    ],
    specs: [
      { label: "Sizes", value: "Fr 8, 10, 12, 14, 16, 18, 20" },
      { label: "Length", value: "Male (40 cm) / Female (20 cm)" },
      { label: "Tip Design", value: "Closed rounded atraumatic tip with 2 lateral eyes" },
      { label: "Material", value: "Medical Grade PVC (DEHP-Free)" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "tur-set",
    name: "TUR SET",
    category: "Urology",
    categoryId: "urology",
    desc: "Heavy-duty Transurethral Resection (TUR) irrigation set with dual/quad piercing spikes for continuous endoscopic bladder irrigation.",
    image: "/Urology/image7.jpg",
    badge: "High-Flow Irrigation",
    features: [
      "Dual large-bore spikes enable seamless switching between irrigation fluid bags without flow interruption",
      "Extra-wide tubing diameter delivers maximum hydrostatic flow rate for clear endoscopic vision",
      "Heavy-duty roller clamp allows precise control of irrigation velocity",
      "Flexible silicone-like adapter fits all cystoscopes and resectoscopes",
      "Sterile and non-pyrogenic for operating theater use",
    ],
    specs: [
      { label: "Configuration", value: "Y-Type (2 Spikes) or 4-Spike manifold" },
      { label: "Tubing Size", value: "Extra wide bore 10mm OD high-flow tubing" },
      { label: "Clamps", value: "Smooth sliding roller clamps" },
      { label: "Connector", value: "Flexible catheter / cystoscope adapter" },
      { label: "Sterilization", value: "ETO Sterile" },
    ],
  },
  {
    id: "urine-culture-container",
    name: "URINE CULTURE CONTAINER",
    category: "Urology",
    categoryId: "urology",
    desc: "Leak-proof sterile urine specimen container with leak-tight screw cap, frosted writing label, and graduated volume markings.",
    image: "/Urology/image8.jpg",
    badge: "100% Leak-Proof",
    features: [
      "Precision-molded threaded screw cap provides 100% leak-proof airtight seal during transport",
      "Transparent polypropylene container with clear molded volume graduations",
      "Pre-printed label for patient name, room, date, and physician details",
      "Chemically resistant to urine preservatives and cold storage",
      "Ideal for microbiology urine cultures and routine urinalysis",
    ],
    specs: [
      { label: "Volumes", value: "30 ml, 60 ml, 100 ml" },
      { label: "Cap Type", value: "Ribbed leak-proof screw cap (Red / Yellow)" },
      { label: "Material", value: "Ultra-pure Polypropylene (PP)" },
      { label: "Label", value: "Pre-printed patient identification label" },
      { label: "Sterilization", value: "Gamma / EO Sterile" },
    ],
  },
  {
    id: "foley-balloon-catheter",
    name: "FOLEY BALLOON CATHETER",
    category: "Urology",
    categoryId: "urology",
    desc: "2-way and 3-way silicone-coated latex Foley balloon catheter with symmetrical inflation balloon and color-coded inflation valve.",
    image: "/Urology/image9.jpg",
    badge: "Symmetrical Balloon",
    features: [
      "Symmetrical balloon expands evenly in all directions to prevent bladder neck trauma",
      "Smooth silicone elastomer coating prevents encrustation and minimizes tissue irritation",
      "Reinforced non-collapsible drainage channel maintains high drainage flow",
      "Color-coded valve for instant size identification",
      "Individual sterile blister packaging ensures 5-year sterility",
    ],
    specs: [
      { label: "Types Available", value: "2-Way / 3-Way" },
      { label: "Sizes", value: "Fr 12, 14, 16, 18, 20, 22, 24, 26" },
      { label: "Balloon Capacity", value: "5ml - 30ml" },
      { label: "Coating", value: "Hydrophobic Medical Silicone" },
      { label: "Valve Type", value: "Hard plastic / soft rubber luer valve" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "life-care-urine-bag",
    name: "LIFE CARE URINE BAG",
    category: "Urology",
    categoryId: "urology",
    desc: "Premium reinforced clinical urine collection bag with enhanced welding seams, dog-bone sample port, and push-pull bottom valve.",
    image: "/Urology/image.jpg",
    badge: "Double-Sealed Seams",
    features: [
      "Double-sealed heavy duty seams prevent leakage under high fluid volume",
      "Clear high-contrast graduations for accurate volume readings",
      "Push-pull drainage outlet enables single-handed emptying",
      "Top universal eyelets fit all hospital mounting frames",
      "Kink-proof flexible medical tubing",
    ],
    specs: [
      { label: "Volume", value: "2000 ml" },
      { label: "Tube Length", value: "100 cm kink-proof PVC" },
      { label: "Sampling Port", value: "Self-sealing needleless port" },
      { label: "Material", value: "Double-welded PVC" },
      { label: "Sterility", value: "Sterile EO" },
    ],
  },
  {
    id: "urine-collection-bag-standard",
    name: "URINE COLLECTION BAG",
    category: "Urology",
    categoryId: "urology",
    desc: "General clinical urine collection bag designed for bedside drainage, post-operative monitoring, and home healthcare.",
    image: "/products/hero_medical_products.png",
    badge: "Clinical Standard",
    features: [
      "Integrated one-way non-return valve protects against urinary tract infections",
      "Conical stepped connector ensures tight leak-free fit with all catheter types",
      "Soft medical PVC sheets with high tensile strength",
      "Economical and dependable for routine hospital use",
      "Clear front sheet with calibrated volume scale",
    ],
    specs: [
      { label: "Volume", value: "2000 ml" },
      { label: "Tubing Length", value: "90 cm" },
      { label: "Valve Type", value: "Non-return valve" },
      { label: "Connector", value: "Stepped universal connector" },
      { label: "Sterilization", value: "ETO Gas" },
    ],
  },
  {
    id: "pressure-monitoring-line-urology",
    name: "PRESSURE MONITORING LINE",
    category: "Urology",
    categoryId: "urology",
    desc: "Urological high-pressure monitoring line for urodynamic testing, intravesical pressure recording, and cystometry.",
    image: "/products/iv_infusion_set.png",
    badge: "Urodynamic Testing",
    features: [
      "Non-distensible rigid wall provides faithful transmission of intravesical and urethral pressures",
      "Transparent construction enables rapid debubbling and fluid verification",
      "Precision luer lock fittings eliminate leakages during urodynamic diagnostic testing",
      "Compatible with all standard urodynamic diagnostic equipment",
      "DEHP-free formulation",
    ],
    specs: [
      { label: "Length", value: "100 cm / 150 cm" },
      { label: "Pressure Rating", value: "Up to 300 psi" },
      { label: "Fittings", value: "Male-to-Female Luer Lock" },
      { label: "Material", value: "Rigid Polyurethane / PVC" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "corrugated-drainage-sheet-urology",
    name: "CORRUGATED DRAINAGE SHEET",
    category: "Urology",
    categoryId: "urology",
    desc: "Flexible medical-grade PVC/rubber corrugated wound drainage sheet for passive capillary drainage in pelvic and urological surgeries.",
    image: "/products/hero_medical_products.png",
    badge: "Radiopaque Drainage",
    features: [
      "Parallel corrugated channels promote rapid capillary drainage of surgical exudates and blood",
      "X-ray opaque line throughout length allows radiographic verification",
      "Easily cut with sterile surgical scissors to custom required dimensions",
      "Soft, tissue-friendly material prevents tissue adherence",
      "Sterile individual peel-open blister packaging",
    ],
    specs: [
      { label: "Dimensions", value: "25 mm x 300 mm / 50 mm x 300 mm" },
      { label: "Material", value: "Radiopaque Medical Grade PVC / Polymer" },
      { label: "Sterilization", value: "ETO Sterile" },
      { label: "Packaging", value: "Peel-open pouch, Box of 20" },
    ],
  },

  /* ═══════════════════════════════════════════════════════════════════
     4. GYNECOLOGY (3 Products)
     ═══════════════════════════════════════════════════════════════════ */
  {
    id: "umbilical-cord-clamp",
    name: "UMBILICAL CORD CLAMP",
    category: "Gynecology",
    categoryId: "gynecology",
    desc: "Sterile single-use umbilical cord clamp with dual-grip interlocking teeth, security lock mechanism, and finger guard.",
    image: "/products/hero_medical_products.png",
    badge: "Interlocking Teeth",
    features: [
      "Precision interlocking serrations apply uniform compression across the umbilical cord to prevent bleeding",
      "Security lock clicks firmly into place and cannot be reopened accidentally",
      "Grooved finger grip surfaces ensure non-slip placement during delivery",
      "Safe, rounded edges protect newborn skin from scratches",
      "Biocompatible, non-toxic medical polymer formulation",
    ],
    specs: [
      { label: "Material", value: "High-Impact Medical Grade Polypropylene" },
      { label: "Locking", value: "Irreversible interlocking double teeth" },
      { label: "Sterility", value: "EO Gas (ISO 11135)" },
      { label: "Packaging", value: "Individual sterile blister pack, Box of 100" },
      { label: "Certifications", value: "CE Marked / ISO 13485" },
    ],
  },
  {
    id: "umbilical-cord-clamp-reusable",
    name: "UMBILICAL CORD CLAMP REUSABLE",
    category: "Gynecology",
    categoryId: "gynecology",
    desc: "Heavy-duty autoclavable umbilical cord clamp manufactured from medical-grade surgical polymer with secure spring-hinge retention.",
    image: "/products/hero_medical_products.png",
    badge: "Autoclavable Polymer",
    features: [
      "Engineered for repeated autoclaving cycles without loss of clamping tension",
      "Strong uniform clamping pressure seals cord vessels reliably",
      "Ergonomic handle design facilitates precise obstetric placement",
      "Smooth medical finish prevents bacterial adhesion",
      "Highly economical for maternity centers and hospitals",
    ],
    specs: [
      { label: "Material", value: "Autoclavable Medical Polymer" },
      { label: "Sterilization", value: "Steam Autoclave (134°C) / ETO" },
      { label: "Locking Type", value: "Releasable locking ratchet" },
      { label: "Standard", value: "ISO 13485" },
      { label: "Packaging", value: "Non-sterile bulk / Individual pack" },
    ],
  },
  {
    id: "umbilical-catheter",
    name: "UMBILICAL CATHETER",
    category: "Gynecology",
    categoryId: "gynecology",
    desc: "Radiopaque polyurethane/PVC neonatal umbilical vessel catheter (UVC/UAC) for arterial and venous access in critically ill newborns.",
    image: "/products/hero_medical_products.png",
    badge: "Neonatal ICU Access",
    features: [
      "Essential for neonatal ICU arterial blood pressure monitoring, blood sampling, and parenteral infusion",
      "Clear, crisp centimeter graduations starting at 1cm for precise insertion depth control",
      "Full radiopaque stripe for exact X-ray location confirmation",
      "Satin-smooth surface minimizes vessel endothelial trauma",
      "Luer lock female hub for secure connection to infusion manifolds",
    ],
    specs: [
      { label: "Sizes Available", value: "2.5 Fr, 3.5 Fr, 5.0 Fr, 8.0 Fr" },
      { label: "Length", value: "37 cm / 40 cm" },
      { label: "Markings", value: "1 cm accurate depth markings" },
      { label: "Tip Type", value: "Atraumatic polished rounded tip" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },

  /* ═══════════════════════════════════════════════════════════════════
     5. GASTROENTEROLOGY (3 Products)
     ═══════════════════════════════════════════════════════════════════ */
  {
    id: "ryles-tube",
    name: "RYLES TUBE",
    category: "Gastroenterology",
    categoryId: "gastroenterology",
    desc: "Nasogastric feeding and stomach aspiration tube with radio-opaque line, 4 lateral eyes, and lead/tungsten weighted tip.",
    image: "/products/hero_medical_products.png",
    badge: "Weighted Distal Tip",
    features: [
      "Built-in metal weights facilitate smooth peristaltic passage into the stomach",
      "Four offset lateral eyes prevent blockage during stomach aspiration and feeding",
      "Prominent depth ring markings allow accurate assessment of tube placement",
      "Radio-opaque X-ray line throughout length for position verification",
      "Color-coded dual-purpose funnel connector with attached plug",
    ],
    specs: [
      { label: "Sizes Available", value: "Fr 8, 10, 12, 14, 16, 18, 20" },
      { label: "Length", value: "105 cm" },
      { label: "Depth Rings", value: "Markings at 50, 60, 70, 80, 90 cm" },
      { label: "Tip Design", value: "Closed distal end with metal ball weights" },
      { label: "Material", value: "Low-toxicity Medical Grade PVC" },
      { label: "Sterilization", value: "EO Sterile" },
    ],
  },
  {
    id: "infant-feeding-tube",
    name: "INFANT FEEDING TUBE",
    category: "Gastroenterology",
    categoryId: "gastroenterology",
    desc: "Ultra-soft neonatal and pediatric enteral feeding tube with graduated depth markings, atraumatic tip, and luer mount cap.",
    image: "/products/hero_medical_products.png",
    badge: "Ultra-Soft Neonatal",
    features: [
      "Specially formulated ultra-soft medical PVC prevents esophageal mucosal irritation in infants",
      "Two lateral eyes maximize nutritional formula flow and reduce clogging risk",
      "Centimeter markings from 5cm to 40cm facilitate precise positioning",
      "Female luer hub fits feeding syringes and enteral pump lines",
      "Individual sterile blister pouch guarantees safe clinical feeding",
    ],
    specs: [
      { label: "Sizes", value: "Fr 4, 5, 6, 7, 8, 10" },
      { label: "Lengths Available", value: "40 cm, 50 cm, 100 cm" },
      { label: "Tip Design", value: "Closed rounded smooth tip with 2 lateral eyes" },
      { label: "Connector", value: "Female luer mount with attached plug" },
      { label: "Material", value: "DEHP-Free Medical PVC" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "infant-mucus-extractor",
    name: "INFANT MUCUS EXTRACTOR",
    category: "Gastroenterology",
    categoryId: "gastroenterology",
    desc: "Sterile infant mucus aspirator equipped with 25ml transparent specimen container, suction catheter, and bacterial barrier filter.",
    image: "/products/hero_medical_products.png",
    badge: "Bacterial Barrier Filter",
    features: [
      "Designed for immediate aspiration of mucus and amniotic fluid from newborn airways",
      "Transparent 25ml container allows instant visual inspection of aspirate volume and color",
      "In-line hydrophobic barrier protects clinician from accidental fluid ingestion",
      "Includes spare screw cap to seal container for microbiological laboratory analysis",
      "Soft catheter tip protects delicate neonatal airway mucosa",
    ],
    specs: [
      { label: "Chamber Volume", value: "25 ml graduated container" },
      { label: "Catheter Size", value: "Fr 10 / Fr 12 with funnel connector" },
      { label: "Filter Type", value: "Hydrophobic bacterial barrier in suction line" },
      { label: "Spare Cap", value: "Additional screw cap for lab transport" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },

  /* ═══════════════════════════════════════════════════════════════════
     6. CARDIOLOGY (2 Products)
     ═══════════════════════════════════════════════════════════════════ */
  {
    id: "high-pressure-line-cardiology",
    name: "HIGH PRESSURE LINE",
    category: "Cardiology",
    categoryId: "cardiology",
    desc: "High-pressure braided / rigid angiography line capable of withstanding up to 1200 psi for contrast media injection in cardiac catheterization labs.",
    image: "/products/iv_infusion_set.png",
    badge: "1200 PSI Rated",
    features: [
      "Heavy-duty pressure rating (1200 psi) handles power injector pulsatile pressures safely",
      "Rotating male luer lock allows 360-degree connection without twisting the catheter line",
      "Crystal clear polyurethane allows effortless bubble detection during contrast media flushing",
      "Zero internal compliance prevents pressure damping during hemodynamic monitoring",
      "Compatible with all standard contrast manifolds and power injectors",
    ],
    specs: [
      { label: "Pressure Rating", value: "1200 psi (83 bar)" },
      { label: "Lengths Available", value: "50 cm, 100 cm, 120 cm, 150 cm, 200 cm" },
      { label: "Fittings", value: "Rotating Male Luer to Fixed Female Luer Lock" },
      { label: "Material", value: "High-density Polyurethane / PVC" },
      { label: "Sterilization", value: "ETO Gas" },
    ],
  },
  {
    id: "cardio-thoracic-vascular-surgery",
    name: "CARDIO-THORACIC AND VASCULAR SURGERY",
    category: "Cardiology",
    categoryId: "cardiology",
    desc: "Comprehensive cardiovascular surgical disposable kit including thoracic drainage catheters, vascular loops, and cardiopulmonary bypass accessories.",
    image: "/products/hero_medical_products.png",
    badge: "Open-Heart Kit",
    features: [
      "Premium clinical grade components packaged for open-heart and vascular procedures",
      "Thoracic catheters feature radiopaque line and large oval eyes for maximum chest drainage",
      "Silicone vascular loops provide atraumatic vessel identification and retraction",
      "Heavy-duty cardiotomy suction tips with stainless steel shaft",
      "Validated sterility assurance level (SAL 10^-6)",
    ],
    specs: [
      { label: "Components", value: "Thoracic Catheters (Fr 20-36), Vascular Occlusion Loops, Suction Tips" },
      { label: "Standards", value: "ISO 13485 & CE Marked" },
      { label: "Material", value: "Medical Grade Silicone & PVC" },
      { label: "Sterilization", value: "ETO Gas" },
      { label: "Packaging", value: "Double sterile surgical wrap" },
    ],
  },

  /* ═══════════════════════════════════════════════════════════════════
     7. GENERAL SURGICAL DISPOSABLES (6 Products)
     ═══════════════════════════════════════════════════════════════════ */
  {
    id: "yankauer-suction-kit",
    name: "YANKAUER SUCTION KIT",
    category: "General Surgical Disposables",
    categoryId: "surgical",
    desc: "Ergonomic rigid transparent Yankauer suction handle complete with 2.5m / 3m ribbed suction connecting tube for intraoperative fluid evacuation.",
    image: "/products/hero_medical_products.png",
    badge: "Crown Tip Handle",
    features: [
      "Shatterproof transparent handle provides clear visualization of evacuated fluids",
      "Ergonomic grip with optional thumb suction control vent for instant suction regulation",
      "Heavy-duty ribbed tubing prevents collapse under maximum operating room vacuum",
      "Universal funnel connectors fit all standard surgical suction canisters",
      "Smooth rounded crown tip prevents tissue suction trauma",
    ],
    specs: [
      { label: "Handle Type", value: "Crown Tip / Plain Tip with Vacuum Control Vent" },
      { label: "Tubing Length", value: "250 cm / 300 cm Star Lumen" },
      { label: "Material", value: "Shatter-resistant transparent resin + PVC" },
      { label: "Sterilization", value: "EO Gas (ISO 11135)" },
      { label: "Packaging", value: "Sterile Double Blister Pack" },
    ],
  },
  {
    id: "corrugated-drainage-sheet-surgical",
    name: "CORRUGATED DRAINAGE SHEET",
    category: "General Surgical Disposables",
    categoryId: "surgical",
    desc: "Flexible corrugated surgical drainage sheet for capillary wound exudate evacuation and post-operative hematoma prevention.",
    image: "/products/hero_medical_products.png",
    badge: "Capillary Drainage",
    features: [
      "Corrugated ribs create continuous capillary pathways for reliable passive fluid drainage",
      "Easily cut to any required length or shape with sterile surgical scissors",
      "Radiopaque line throughout enables postoperative X-ray verification",
      "Non-adherent finish minimizes patient discomfort during dressing changes",
      "Sterile individual blister packaging",
    ],
    specs: [
      { label: "Size", value: "25 mm x 300 mm / 50 mm x 300 mm" },
      { label: "Material", value: "Medical Grade PVC / Polymer" },
      { label: "Sterilization", value: "EO Gas" },
      { label: "Packaging", value: "Sterile Blister, Box of 20" },
    ],
  },
  {
    id: "close-wound-suction-kit-vac-set",
    name: "CLOSE WOUND SUCTION KIT / VAC SET",
    category: "General Surgical Disposables",
    categoryId: "surgical",
    desc: "High-vacuum closed wound drainage unit with 400ml spring bellows / bellows bottle, trocar needle, and perforated silicone/PVC drain.",
    image: "/products/hero_medical_products.png",
    badge: "Constant Negative Pressure",
    features: [
      "Negative pressure bellows maintains constant gentle suction to promote rapid wound healing",
      "Sharp curved stainless steel trocar allows effortless subcutaneous tunneling",
      "Multi-perforated radiopaque drain tube ensures thorough fluid evacuation from wound bed",
      "Stepped connector accommodates multiple drain sizes",
      "Integrated one-way valve prevents backflow of drained exudate",
    ],
    specs: [
      { label: "Bellows Volume", value: "400 ml / 600 ml" },
      { label: "Trocar Needle", value: "Curved stainless steel trocar needle" },
      { label: "Drain Sizes", value: "Fr 10, 12, 14, 16, 18 perforated" },
      { label: "Material", value: "Medical Grade PVC / Silicone" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "mini-vac-set",
    name: "MINI VAC SET",
    category: "General Surgical Disposables",
    categoryId: "surgical",
    desc: "Compact 30ml / 50ml low-vacuum wound drainage system with mini bellows and fine needle for plastic, dental, and minor surgical procedures.",
    image: "/products/hero_medical_products.png",
    badge: "Ambulatory Mini Bellows",
    features: [
      "Compact lightweight design attaches comfortably to patient clothing for ambulatory recovery",
      "Gentle low-vacuum suction prevents tissue collapse in delicate surgical sites",
      "Ideal for facial, thyroid, breast, and orthopedic minor surgeries",
      "Transparent calibrated mini reservoir for precise fluid measurement",
      "Complete sterile kit ready for immediate deployment",
    ],
    specs: [
      { label: "Volume", value: "30 ml / 50 ml" },
      { label: "Needle", value: "Stainless steel mini trocar" },
      { label: "Drain Tube", value: "Fr 6 / Fr 8 fine silicone/PVC" },
      { label: "Sterility", value: "EO Sterile" },
      { label: "Packaging", value: "Individual Sterile Kit" },
    ],
  },
  {
    id: "disposable-apparels",
    name: "DISPOSABLE APPARELS",
    category: "General Surgical Disposables",
    categoryId: "surgical",
    desc: "Surgical disposable PPE kit including SMS sterile surgical gowns, surgeon caps, fluid-repellent face masks, and shoe covers.",
    image: "/products/hero_medical_products.png",
    badge: "AAMI Level 3 Barrier",
    features: [
      "High-barrier SSMMS non-woven fabric provides superior liquid repellency and microbial resistance",
      "Breathable, lint-free material ensures surgeon comfort during lengthy operations",
      "Ultrasonic welded seams and knitted cuffs for complete sterile barrier integrity",
      "Latex-free and hypoallergenic formulation",
      "Individual sterile wrap with hand towels",
    ],
    specs: [
      { label: "Materials", value: "45-60 GSM SSMMS / SMS Non-Woven Fabric" },
      { label: "Protection", value: "AAMI Level 3 / Level 4 Fluid Barrier" },
      { label: "Certifications", value: "ISO 13485, CE, EN 13795" },
      { label: "Inclusions", value: "Surgical Gown, Cap, Mask, Shoe Covers" },
      { label: "Sterilization", value: "EO Gas" },
    ],
  },
  {
    id: "abdominal-drainage-kit",
    name: "ABDOMINAL DRAINAGE KIT",
    category: "General Surgical Disposables",
    categoryId: "surgical",
    desc: "Sterile closed abdominal paracentesis and drainage kit featuring soft radio-opaque catheter, collection bag, and scalpel/trocar.",
    image: "/products/hero_medical_products.png",
    badge: "Ascites Drainage",
    features: [
      "Engineered for rapid relief of ascites and post-operative abdominal fluid collection",
      "Soft catheter with large oval eyes maximizes flow of viscous fluids and fibrin",
      "Complete procedure kit reduces prep time in emergency and surgical wards",
      "Double-welded collection bag with bottom drain valve",
      "Full radiopaque X-ray identification stripe",
    ],
    specs: [
      { label: "Catheter Sizes", value: "Fr 20 to Fr 36 with multiple lateral holes" },
      { label: "Bag Capacity", value: "2000 ml drainage bag with bottom outlet" },
      { label: "Accessories Included", value: "Scalpel, fixation clamp, connecting tube" },
      { label: "Sterilization", value: "EO Gas" },
      { label: "Standard", value: "ISO 13485 Compliant" },
    ],
  },

  /* ═══════════════════════════════════════════════════════════════════
     8. MECCA LABS (5 Products)
     ═══════════════════════════════════════════════════════════════════ */
  {
    id: "pharmaceutical-product-list",
    name: "PHARMACEUTICAL PRODUCT LIST",
    category: "Mecca Labs",
    categoryId: "mecca-labs",
    desc: "Certified pharmaceutical formulations, sterile injectable solutions, intravenous infusions, and finished dosage forms manufactured under WHO-GMP compliance.",
    image: "/products/hero_medical_products.png",
    badge: "WHO-GMP Formulations",
    features: [
      "Comprehensive WHO-GMP certified pharmaceutical formulation portfolio",
      "State-of-the-art sterile cleanrooms with HEPA filtration and automated filling",
      "Fully documented Certificate of Analysis (COA) and regulatory dossiers (CTD/eCTD format)",
      "Rigorous stability testing under Zone IVB climatic conditions",
      "Exported to 50+ global health authorities and hospital systems",
    ],
    specs: [
      { label: "Certifications", value: "WHO-GMP, ISO 9001:2015" },
      { label: "Dosage Forms", value: "Injectables, Sterile Infusions, Tablets, Capsules, Liquid Orals" },
      { label: "Packaging", value: "Alu-Alu, Blister, Glass Vials, Infusion Bottles" },
      { label: "Quality Grade", value: "Pharmacopeial Grade (USP / BP / IP)" },
      { label: "Facility", value: "Class 10,000 / Class 100K Cleanroom Units" },
    ],
  },
  {
    id: "nutraceutical-product-list-domestic",
    name: "NUTRACEUTICAL PRODUCT LIST (Domestic)",
    category: "Mecca Labs",
    categoryId: "mecca-labs",
    desc: "Premium domestic nutritional supplements, dietary formulations, vitamin blends, and wellness solutions registered with FSSAI.",
    image: "/products/hero_medical_products.png",
    badge: "FSSAI & ISO 22000",
    features: [
      "Scientifically validated domestic nutritional supplements targeting immunity, joint health, and vitality",
      "Premium bioactive ingredients with standardized herbal extracts",
      "High-speed automated encapsulation and blister packaging lines",
      "Strict batch testing for purity, potency, and dissolution rates",
      "Customized packaging and private labeling for domestic distribution brands",
    ],
    specs: [
      { label: "Regulatory", value: "FSSAI Approved & ISO 22000" },
      { label: "Formats Available", value: "Softgels, Capsules, Effervescent Tablets, Gummies, Protein Powders" },
      { label: "Purity Testing", value: "100% Non-GMO, Heavy-Metal Tested" },
      { label: "Shelf Life", value: "24 - 36 Months" },
      { label: "Origin", value: "Made in India (Kalol / Chhatral / Jodhpur)" },
    ],
  },
  {
    id: "nutraceuticals-product-list-export",
    name: "NUTRACEUTICALS PRODUCT LIST (Export)",
    category: "Mecca Labs",
    categoryId: "mecca-labs",
    desc: "High-potency global export grade nutraceutical formulations adhering to international dietary supplement standards and regulatory documentation.",
    image: "/products/hero_medical_products.png",
    badge: "Export cGMP Compliant",
    features: [
      "Formulated specifically for international regulatory compliance and climatic stability",
      "Standardized botanical extracts, vitamins, minerals, and amino acid complexes",
      "Complete export dossier support and bilingual packaging capabilities",
      "Multi-stage microbiological and heavy metal quality validation",
      "Scalable high-capacity production for multinational brand partners",
    ],
    specs: [
      { label: "Global Compliance", value: "US-FDA cGMP, Halal, Kosher Certified" },
      { label: "Target Markets", value: "Middle East, CIS, Africa, Southeast Asia, Latin America" },
      { label: "Formats", value: "Tablets, Hard/Soft Gelatin Capsules, Sachets, Syrups" },
      { label: "Documentation", value: "Free Sale Certificate (FSC), Halal, COA, Stability Data" },
      { label: "Export Footprint", value: "Exporting to 50+ Global Countries" },
    ],
  },
  {
    id: "milk-product-list",
    name: "MILK PRODUCT LIST",
    category: "Mecca Labs",
    categoryId: "mecca-labs",
    desc: "High-grade dairy derivatives, specialized milk protein concentrates, whey isolates, and nutritional dairy ingredients for clinical and dietary food industries.",
    image: "/products/hero_medical_products.png",
    badge: "HACCP & Clinical Grade",
    features: [
      "Superior microbiological purity suitable for clinical nutrition and enteral feed formulations",
      "High biological value and optimal amino acid profile",
      "Instantized for rapid dispersion and smooth solubility in water and milk",
      "Strictly free from synthetic hormones, antibiotics, and contaminants",
      "Complete traceability from dairy source to finished ingredient",
    ],
    specs: [
      { label: "Product Range", value: "Whey Protein Isolate (WPI 90), Whey Protein Concentrate (WPC 80), Skimmed Milk Powder, Caseinates" },
      { label: "Standards", value: "ISO 22000, HACCP, FSSAI" },
      { label: "Processing", value: "Cross-Flow Microfiltered, Low Lactose, Instantized" },
      { label: "Packaging", value: "25kg Multi-Wall Kraft Bags / Bulk Drums" },
      { label: "Application", value: "Clinical Nutrition, Enteral Feeds, Sports Supplements" },
    ],
  },
  {
    id: "cosmeceutical-product-list",
    name: "COSMECEUTICAL PRODUCT LIST",
    category: "Mecca Labs",
    categoryId: "mecca-labs",
    desc: "Dermatologically formulated cosmeceutical skincare and therapeutic personal care products manufactured in certified cleanroom cosmetic facilities.",
    image: "/products/hero_medical_products.png",
    badge: "ISO 22716 Cosmetic GMP",
    features: [
      "Advanced clinical formulations combining active dermatological ingredients with natural botanicals",
      "Formulated for maximum dermal bioavailability and proven therapeutic efficacy",
      "Hypoallergenic, sulfate-free, and paraben-free clean formulations",
      "Full private label development including custom fragrance, texture, and packaging",
      "Exported across global dermatology clinics and retail cosmetic brands",
    ],
    specs: [
      { label: "Product Types", value: "Dermatological Serums, Therapeutic Creams, Sunscreens, Cleansers, Anti-Aging Formulations" },
      { label: "Standards", value: "ISO 22716 (Cosmetic GMP) & Cruelty-Free" },
      { label: "Clinical Testing", value: "Dermatologist Tested, Non-Comedogenic, Paraben-Free" },
      { label: "Packaging Formats", value: "Airless Pumps, Tubes, Dropper Bottles, Jars" },
      { label: "OEM Options", value: "Custom Formulation & Private Label Branding" },
    ],
  },
];

export function getProductById(id: string): ProductItem | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getCategoryById(categoryId: string): CategoryItem | undefined {
  return CATEGORIES.find((c) => c.id === categoryId);
}

export function getProductsByCategoryId(categoryId: string): ProductItem[] {
  if (categoryId === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.categoryId === categoryId);
}

export function getRelatedProducts(currentId: string, limit = 3): ProductItem[] {
  const current = getProductById(currentId);
  if (!current) return PRODUCTS.filter((p) => p.id !== currentId).slice(0, limit);

  // Prioritize products in the same category
  const sameCategory = PRODUCTS.filter(
    (p) => p.categoryId === current.categoryId && p.id !== currentId
  );
  if (sameCategory.length >= limit) {
    return sameCategory.slice(0, limit);
  }

  const otherProducts = PRODUCTS.filter(
    (p) => p.categoryId !== current.categoryId && p.id !== currentId
  );
  return [...sameCategory, ...otherProducts].slice(0, limit);
}
